---
version: "3"
services:
 devopsdb:
   image: nallamothubhavya14/my-repo:dbimage
   ports:
     - "3306:3306"
   deploy:
     replicas: 3

 application:
   image: nallamothubhavya14/my-repo:appimage
   ports:
     - "1234:8080"
   deploy:
     replicas: 3
   depends_on:
     - "devopsdb"
